### ISSUE TITLE
Domain fixed by configuration for short URLs 

### ISSUE THREAD

**Issue by julpec** [ldidry/lstu#12]
I try in english first, french after that ;)

I would like to reach lstu from one domaine (i.e. https://private.domain.org) and create short links for another domain (i.e. http://public.domain.org). It should be good if we don't want that others create short links for our domain.
On the public domain, I have separate two instance with apache but it should be good to deal with that in the lstu configuration. Here is my Apache conf : 

```
ServerName public.domaine.org
DocumentRoot /var/www/lstu
	<LocationMatch "^/$">
                AuthType Basic
		… (rest of conf)
	</LocationMatch>
	<LocationMatch "^/.*">
		allow from all
	</LocationMatch>

ProxyPass / http://localhost:8888/
ProxyPassReverse / http://localhost:8888/
ProxyVia On
ProxyRequests Off
ProxyPreserveHost on
```

J'aimerai savoir si il est possible que Lstu fournisse toujours des
liens courts basés sur un même domaine, bien qu'on accède à Lstu par un
autre domaine.
Par exemple, j'aimerai que les membres admin de ma structure puissent
accéder à Lstu par https://prive.domaine.org/lstu (domaine qui est sous
authentification Apache) et que le public puisse profiter des liens
courts sans s'authentifier (adresses du type
http://public.domaine.org/le-nom-de-mon-lien-court.)

Pour la partie publique, j'arrive à limiter l'accès à la saisie de liens
courts du côté apache tout en laissant l'accès aux liens courts en
eux-même :

```
ServerName public.domaine.org
DocumentRoot /var/www/lstu
	<LocationMatch "^/$">
		AuthType Basic
		… (reste de la conf…)
	</LocationMatch>
	<LocationMatch "^/.*">
		allow from all
	</LocationMatch>

ProxyPass / http://localhost:8888/
ProxyPassReverse / http://localhost:8888/
ProxyVia On
ProxyRequests Off
ProxyPreserveHost on
```

**Comment by ldidry** [comment]
Will be fixed in next release (soon :smile:)

**Comment by ldidry** [comment]
Done (update your conf file, it has changed a lot). <https://git.framasoft.org/luc/lstu/blob/master/ChangeLog>
