### ISSUE TITLE
XSS vulnerability on url

### ISSUE THREAD

**Issue by matheod** [ldidry/lstu#15]
Try entering : ``http://google.fr?a=<u>xss`` in the url field.

It will show : ``http://google.fr?a=xss n'est pas une URL valide.`` with ``xss n'est pas une URL valide.`` underlined (and by the way this should be a valid url).

**Comment by ldidry** [comment]
Mmh, this is not really a valid URL since the parameters are not url encoded.

I removed the xss vulnerability (not pushed yet). I'll try to find a way to automatically url encode such parameters.

**Comment by ldidry** [comment]
Will be fully fixed in the next release ;-)

**Comment by ldidry** [comment]
Done. <https://git.framasoft.org/luc/lstu/blob/master/ChangeLog>
