### ISSUE TITLE
How to add an uri ?

### ISSUE THREAD

**Issue by lokiiiii** [ldidry/lstu#16]
Bonjour,
J'essaye depuis 3 jours d'installer lstu sur ma debian 7.5.
J'ai un soucis au niveau de la conf nginx. J'aimerai beaucoup pouvoir taper lstu depuis http://mondomaine.fr/lstu au lieu de http://mondomaine.fr.
Après deux jours de galère j'ai réussi à obtenir la page d'accueil de lstu sur http://mondomaine.fr/lstu, mais lorsque je fais une requête, j'obtiens une 404 avec l'url : http://mondomaine.fr/a (sans rien derrière, et sans le "/lstu")
Si jamais tu pouvais jeter un petit coup d'oeil, j'ai ouvert un topic à l'adresse suivante avec les confs nginx:
http://mondedie.fr/viewtopic.php?id=6605
Merci beaucoup et encore félicitations pour le soft! :)

**Comment by ldidry** [comment]
On m'a posé la même question pour [Lutim](https://git.framasoft.org/lutim) et j'avais mamaillé un truc dessus, que j'ai retransposé pour Lstu. Ce sera pour la prochaine release (dans pas trop longtemps).

**Comment by ldidry** [comment]
Done (mettre à jour le fichier de conf, il a pas mal changé). <https://git.framasoft.org/luc/lstu/blob/master/ChangeLog>
