### ISSUE TITLE
Do not force too many dependancies

### ISSUE THREAD

**Issue by tobast** [ldidry/lstu#17]
Hello,

Would it be possible to depend on fewer libraries? For instance, most people will not be interrested in LDAP authentication, and I find it pretty cumbersome to install this as a dependancy on my server when I won't use it. Maybe it would be possible to enable/disable such modules in a configuration file?

Thanks!

**Comment by ldidry** [comment]
I understand your point of view, but I don't know how to do that and it may complexify the maintenance of the software.
