### ISSUE TITLE
When i want to use script functions, i need to install endless packets

### ISSUE THREAD

**Issue by MBadberg** [ldidry/lstu#18]
I wanted to generate my own theme with script/lstu theme new_theme

But there is everytime an error and i don't know, what packets i have to install.
Can you provide a list?

These Packages i've already installed:
ORLite
Apache::Htpasswd
Net::LDAP
Mojolicious

**Comment by ldidry** [comment]
Did you install the dependencies with `carton install` before doing `carton exec ./script/lstu theme your_theme`?

Can you paste the error messages here please?

**Comment by MBadberg** [comment]
ah, okay. no i've not used carton exec. It works! :-) *lol*
